---
title: "Что порешать и почитать"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---

## Занятие 1

Тема: совместное распределение сл.в., характеристики сл.в., биномиальное распределение, распределение Пуассона
 
<a href="seminar1.pdf" title=>Seminar 1</a> 

<a href="lab1.R" title=>Lab session 1</a> 

<a href="hw1.pdf" title=>Home assignment 1</a> 
 
## Занятие 2
 
Тема: непрерывные сл.в., функция плотности, экспоненциальное распределеление, нормальное распределение 
 
<a href="seminar2.pdf" title=>Seminar 2</a>  

Home assignment 2 (обязательное): дорешать из файла Seminar 2 задания 3, 5, 7, 8 + подготовиться к проверочной работе 1 <i class="fa fa-exclamation-circle fa-2x"></i> 

<a href="hw2_optional.pdf" title=>Home assignment 2 (optional) </a> 
 
## Занятие 3

Тема: методы оценивания (метод моментов + метод максимального правдоподобия)

<a href="tvims2_seminar3.pdf" title=>Seminar 3</a> 

Домашнее задание: дорешать из файла Seminar задания 3, 4, 6

<a href="tvims2_hw4.pdf" title=>Домашнее задание 4 (первое сдаваемое)</a>

## Занятие 4

Тема: методы оценивания (метод моментов + метод максимального правдоподобия) + доверительные интервалы повторение

<a href="tvims2_seminar4.pdf" title=>Seminar 4</a> 

<a href="tvims2_hw_bonus.pdf" title=>Bonus</a> 

## Занятие 5

Тема: доверительные интервалы для MLE-оценок, распределение хи-квадрат

<a href="tvims2_sem5.pdf" title=>Seminar 5</a> 

<a href="tvims2_lab3.R" title=>Lab session 3</a> 

<a href="tvims2_hw5.pdf" title=>Домашнее задание 5</a> 

## Занятие 6

Тема: основы проверки статистических гипотез 

<a href="tvims2_seminar6.pdf" title=>Seminar 6</a> 

## Занятие 7 

Тема: основы проверки статистических гипотез + проверочная работа 

<a href="tvims2_hypothesis_testing.pdf" title=>Презентация: проверка гипотез</a> 

Домашнее задание: 

1) выполнить задание, сдаваемое на проверку <a href="https://www.dropbox.com/sh/xt97x9qn66uvx10/AADLVJ5O3So7dc0wIPRt-1Mca?dl=0" title=>Домашнее задание 6 (второе сдаваемое)</a>

2) дорешать задание 3 из <a href="tvims2_seminar6.pdf" title=>Seminar 6</a> 

Reading:

1) обязательное: <a href="https://yadi.sk/i/2d6t-bJK1Rjo2Q" title=>Wackerly</a> Chapter 10 (10.1, 10.2 (про ошибку второго рода можно не читать), 10.6, 10.7)

2) <a href="Cohen_1994.pdf" title=>Cohen</a> 

3) <a href="the ASA's Statement on p-values.pdf" title=>the ASA's Statement on p-values</a>

4) <a href="https://statmodeling.stat.columbia.edu/?s=p-value" title=>интересные дискуссии о p-value -- reflection by Andrew Gelman</a>

## Занятие 8 

Тема: проверка гипотезы о равенстве вариаций. Распределение Фишера

<a href="tvims2_sem7.pdf" title=>Seminar 7</a>

<a href="tvims2_lab_4.R" title=>Lab session 4</a>

<a href="price.dta" title=>Price.dta</a>

<a href="tvims2_hw_7.pdf" title=>Домашнее задание 7</a>

## Занятие 9 

Тема: проверка гипотез (продолжение)

<a href="tvims2_hw8.pdf" title=>Домашнее задание 8</a>

## Занятие 10

<a href="tvims2_hw9.pdf" title=>Домашнее задание 9</a>

## Занятие 11

<a href="tvims2_seminar9.pdf" title=>Seminar 9</a>

<a href="tvims_hw10.pdf" title=>Домашнее задание 10</a>

## Занятие 12 

Тема: модель линейной парной регрессии, МНК-оценки, допущения об ошибках

<a href="tvims2_lecture1.pdf" title=>Lecture notes 1</a>

<a href="tvims2_hw11.pdf" title=>Домашнее задание 11</a>

Reading: 

<a href="Gujarati.pdf" title=>Gujarati, pp. 37 - 73</a>

## Занятие 13 

Тема: модель линейной парной регрессии, проверка статистической значимости оценок коэффициентов, разложение вариации отклика, ANOVA-таблица

<a href="tvims2_seminar1_regression.pdf" title=>Regression. Seminar 1</a>

<a href="tvims2_lecture2.pdf" title=>Lecture notes 2</a>

<a href="tvims2_hw12-2.pdf" title=>Домашнее задание 12</a>

## Занятие 14

Тема: проверка ДЗ + проверочная работа

<a href="tvims2_hw13.pdf" title=>Домашнее задание 13</a>

## Занятие 15

<a href="tvims_hw_14_.pdf" title=>Домашнее задание 14</a>

<a href="hw14.txt" title=>hw14.txt</a>

<a href="Regression_lab1.R" title=>Lab 1</a>

<a href="reg_lab1.dta" title=>Lab 1. Data</a>

## Занятие 16

<a href="Lecture notes 3.pdf" title=>Lecture notes 3</a>

<a href="regression_lab2.R" title=>Lab 2</a>

<a href="https://www.youtube.com/playlist?list=PL49CF3715CB9EF31D" title=>Lectures on linear algebra</a> <i class="fa fa-video-camera fa"></i>

## Занятие 17

Тема: гетероскедастичность и нетипичные наблюдения

Домашнее задание к 31 марта: 

<a href="tvims2_hw_15.pdf" title=>Домашнее задание 15</a>

<a href="hw15.dta" title=>hw15.dta</a>

### Дополнительные главы теории вероятностей и математической статистики

## Занятие 1

<a href="tvims3_intro.pdf" title=>Доп. главы ТВиМС. Введение</a>

<a href="tvims3_Lecture_1.pdf" title=>Занятие 1</a>

<a href="tvims3_Seminar_1.pdf" title=>Семинар 1</a>

<a href="tvims_3_hw_1 .pdf" title=>Домашнее задание 1</a>

<a href="tvims3_solution1.pdf" title=>Разбор задач семинара 1</a>




